"""
RazorShield AI — Centralized Reason Codes Registry
Stable reason codes explaining risk signal output and aggregated risk decisions.
"""


class ReasonCode:
    # Velocity Signals
    HIGH_VELOCITY_1H_COUNT = "HIGH_VELOCITY_1H_COUNT"
    HIGH_VELOCITY_1H_AMOUNT = "HIGH_VELOCITY_1H_AMOUNT"
    HIGH_VELOCITY_24H_COUNT = "HIGH_VELOCITY_24H_COUNT"
    HIGH_VELOCITY_24H_AMOUNT = "HIGH_VELOCITY_24H_AMOUNT"

    # Amount Anomalies
    ABNORMAL_TRANSACTION_AMOUNT = "ABNORMAL_TRANSACTION_AMOUNT"
    HIGH_VALUE_FIRST_TRANSACTION = "HIGH_VALUE_FIRST_TRANSACTION"

    # Geographic Anomalies
    NEW_IP_LOCATION = "NEW_IP_LOCATION"
    IMPLAUSIBLE_TRAVEL_SPEED = "IMPLAUSIBLE_TRAVEL_SPEED"
    GEO_UNVERIFIED = "GEO_UNVERIFIED"

    # Device & Entity Anomalies
    NEW_DEVICE = "NEW_DEVICE"
    DEVICE_ACCOUNT_REUSE = "DEVICE_ACCOUNT_REUSE"
    IP_MULTI_ACCOUNT_CLUSTER = "IP_MULTI_ACCOUNT_CLUSTER"
    CARD_TOKEN_MULTI_ACCOUNT = "CARD_TOKEN_MULTI_ACCOUNT"

    # Payment Behavioral Anomalies
    BIN_HIGH_RISK_MATCH = "BIN_HIGH_RISK_MATCH"
    UNUSUAL_MERCHANT_CATEGORY = "UNUSUAL_MERCHANT_CATEGORY"
    RAPID_RETRY_BURST = "RAPID_RETRY_BURST"

    # ML & Graph Engine Codes
    ISOLATION_FOREST_ANOMALY = "ISOLATION_FOREST_ANOMALY"
    HETEROGENEOUS_RING_CLUSTER = "HETEROGENEOUS_RING_CLUSTER"

    # System & Degraded Mode Codes
    NORMAL_ALL_SYSTEMS = "NORMAL_ALL_SYSTEMS"
    DEGRADED_NO_ML = "DEGRADED_NO_ML"
    DEGRADED_NO_GRAPH = "DEGRADED_NO_GRAPH"
    DEGRADED_RULES_ONLY = "DEGRADED_RULES_ONLY"
